class AppConfig:
    IMAGE_DIR = "images"
    DEFAULT_WORK_VOLTAGE = 1.1
    DEFAULT_TARGET_YEARS = 0.2
    DEFAULT_FAILURE_CRITERIA = 10.0
    DEFAULT_FITTING_POINTS = 5
    DEFAULT_SLOPE_MODE = "average"
    DEFAULT_MODEL_TYPE = "isub"
    DEFAULT_ISUB_WORK_METHOD = "算术平均"
    DEFAULT_QUANTILES = ['t63.2%', 't50%', 't0.1%', 't0.01%', 't0.001%']
    DEFAULT_WINDOW_SIZE = "1300x850"
    DEFAULT_HISTORY_MAX = 10